# src/monitoring/config/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'fraud-detection-app'
    static_configs:
      - targets: ['host.docker.internal:5000']  # For Docker Desktop
        # Use 'localhost:5000' if running locally without Docker
    scrape_interval: 50s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']