# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set current working directory
WORKDIR /usr/Chatbot

# Copy only the requirements.txt initially
COPY requirements.txt /usr/Chatbot/

# Install the required libraries (will only run if requirements.txt changes)
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project files
COPY . /usr/Chatbot/

# Expose the port within Docker 
EXPOSE 5000

# Container start-up command
CMD ["python3", "app.py"]